### PR TITLE
Make it clearer that you need Gorilla Menu.

### PR DESCRIPTION
**Pull request by HyperDondon**
It's confusing for people, including me. I had to look for the post in #pc-mod-releases in the Gorilla Tag Modding Group Discord server.

### CODE REVIEW

**Comment by Arizynx** [comment]
this is now on the README.

**Comment by HyperDondon** [comment]
Closed, because it is now in the README. Pointed out by @RylanFoxins

**Comment by Arizynx** [comment]
> Closed, because it is now in the README. Pointed out by @RylanFoxins

Btw, you were the reason I put it in the README lol

**Comment by HyperDondon** [comment]
> > Closed, because it is now in the README. Pointed out by @RylanFoxins
> 
> Btw, you were the reason I put it in the README lol

alr

**Pull request closed without merging**
